### ISSUE TITLE
It throws a very strange NullPointerException.

### ISSUE THREAD

**Issue by Ray-Eldath** [icela/Castle-game#1]
It throws a very strange NPE like:

```
Exception in thread "main" java.lang.NullPointerException
    at game.map.Room.setBossItem(Room.java:120)
    at game.map.Map.lambda$new$1(Map.java:40)
    at java.util.HashMap.forEach(HashMap.java:1288)
    at game.map.Map.<init>(Map.java:40)
    at game.Game.onCreate(Game.java:42)
    at game.Game.<init>(Game.java:38)
    at view.GUI.<init>(GUI.java:36)
    at view.GUI.main(GUI.java:173)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
```

**Comment by Predator-SD** [comment]
throws......

**Comment by ice1000** [comment]
Let me debug it. :joy: I just wanna rebuild frice engine...

**Comment by ice1000** [comment]
@Predator-SD Do you wanna develop games with us?

**Comment by ice1000** [comment]
bug fix。 closed.

**Comment by ice1000** [comment]
What the hell???
![](http://s.cn.bing.net/th?id=OIP.M53d0686b81fe88a5682b8d5864da06d3o1&w=94&h=108&c=7&rs=1&qlt=90&pid=3.1&rm=2)

I'll review it later.

**Comment by HugoRun** [comment]
未找到BOSS对象

**Comment by lizhaohan001** [comment]
@HugoRun 嗯。。。其实我认为问题是因为... ...呃... ...驱动的一些不为人知的问题。。。 
![](http://i4.buimg.com/8311/f1a43b5e65cfc259.png)
因为上图的debug结果指出statement是空的。。。
但是我驱动已经配置好了啊。。。不知道问题到底出在哪。

**Comment by ice1000** [comment]
@HugoRun
对寒冰引擎感兴趣不，要不要来一起写小游戏啊(ㆁωㆁ*)

**Comment by HugoRun** [comment]
@ice1000 那是啥

**Comment by ice1000** [comment]
@HugoRun 一个JVM原生2D游戏引擎。
[传送门](https://github.com/icela/FriceEngine)

**Comment by ice1000** [comment]
尼玛这都多早以前的历史遗留问题了 closed. :joy:

**Comment by ice1000** [comment]
尼玛这都多早以前的历史遗留问题了 closed. :joy:
